FROM maven:latest AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn test
RUN mvn package

FROM openjdk:latest
WORKDIR /app
COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war .

EXPOSE 8080

CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]